import type { Metadata } from "next";

import "./globals.css";
import "@styles/global.scss";
import Navbar from "@components/Navbar"
import Footer from "@components/Footer"

import CMS from "@utils/CMS";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const genericElement = await CMS.get('genericElement');

  return (
    <html lang="en">
      <body>
        <div className="flex flex-wrap w-full h-full">
          <div className="block w-full">
            <Navbar />
            <main>{children}</main>
          </div>
          <Footer genericElement={genericElement} />
        </div>
      </body>
    </html>
  );
}
